### PR TITLE
Fix carousel

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
After this PR:

- The react element `Carousel` will auto loop ( $\infty$ ) on the three configurations (sometimes I feel like it is slowed, but maybe is a my impression);
- the `emulateTouch` option in the carousel allows us to use the mouse for emulating the touch-screen swipe.
- the space between Carousel and the "Getting started" section is reduced.

In theory, it is possible to customize the react elements that correspond to the left and right arrows in the carousel. I think I'll open a new Issue for this, so I'll think about it in the future. At the moment the ones I present I think are effective solutions.

### CODE REVIEW

**Comment by MatteoRobbiati** [comment]
This can be merged?

**Comment by scarrazza** [comment]
Sure.

**Comment by AleCandido** [comment]
Before merging, I guess you have to solve the conflict with `master`.

**Comment by MatteoRobbiati** [comment]
> Before merging, I guess you have to solve the conflict with `master`.

Yes, I was looking at it. I think that now this is fixed.

**Pull request merged**
