### PR TITLE
From Arial to Ubuntu through Roboto

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
I changed the font: from Arial to Roboto.

### CODE REVIEW

**Comment by scarrazza** [comment]
Yes, I like.

**Comment by AleCandido** [comment]
Please add the font package, and import it in the top-level layout:

https://fontsource.org/docs/guides/nextjs
https://www.npmjs.com/search?q=%40fontsource%2Froboto

**Comment by AleCandido** [comment]
Concerning the code font, you could use [Roboto Mono](https://fontsource.org/fonts/roboto-mono), for consistency, but it is not required.

Personally, I'm quite keen on [Fira Code](https://www.npmjs.com/package/@fontsource/fira-code). [Ligatures](
https://github.com/tonsky/FiraCode) are particularly elegant, but maybe for them there is not a package, so for that we may have to download it.

**Comment by AleCandido** [comment]
Moreover, the most important thing is that the font choice should not been in many places, but in a single one.

The simplest option is just to set the `font-family` once in `body` rule, everywhere else you get from the cascade (that's CSS after all).
But sometimes you might want to reset the font after having changed it. For this, the best option is to set top-level some a [CSS variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties):

```html
<body>
  <section>
    Ciao:
    <article>
      come va?
    </article>
  </section>
</body>
```
```css
body {
  --main-sans: Roboto;
  --main-serif: 'Roboto Serif';
  --default-sans: var(--main-sans), sans-serif;
  --default-serif: var(--main-sans), serif;
  font-family: var(--default-sans);
}

section {
  font-family:  var(--default-serif);
}

article {
  font-family:  var(--default-sans);
}
```

**Comment by MatteoRobbiati** [comment]
Thank you @AleCandido for the suggestions.
I ave a question both for you and @scarrazza: do you like `Roboto Mono` or it is "too much" ? 
Personally I like the mono-space style, but I am not sure it is the best choice in terms of web developing.

**Comment by MatteoRobbiati** [comment]
> Thank you @AleCandido for the suggestions. I ave a question for both you and @scarrazza: do you like `Roboto Mono` or it is "too much" ? Personally I like the mono-space style, but I am not sure it is the best choice in terms of web developing.

Don't think about this. I have just choosen "Ubuntu" font: I really like it and it allows us to propagate the open source philosophy even in fonts.

**Comment by scarrazza** [comment]
Yes, I liked.

**Comment by MatteoRobbiati** [comment]
> Yes, I like it.

Perfect. Now I am trying to add the Ubuntu font into the sphinx configuration file.

**Comment by AleCandido** [comment]
> Personally I like the mono-space style, but I am not sure it is the best choice in terms of web developing.

About the individual font, we can iterate and choose what we prefer.
Instead, about the category:
- *sans-serif* are used by default in web
- *serif* is default for printed books and publications in general; you can use also for web, and there are specific kinds that use that by default (e.g. newspaper websites), and gives a more classic/vintage look, but it is already a non-neutral choice
- *monospaced* is a strong choice: there are several examples, but you declare that you are really code oriented

There are also a few other categories, e.g. *handwritten*-like fonts, but I would reserve those for titles, while the bulk of the text should be something simple.

**Comment by AleCandido** [comment]
This (and resources linked) can help you in motivating and improving your choice:
https://fonts.google.com/knowledge/choosing_type/a_checklist_for_choosing_type

**Review by AleCandido — APPROVED** [review]

**Pull request merged**
